export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_DETAILS_SUCCESS = 'LOAD_DETAILS_SUCCESS';

export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const LOAD_DETAILS_PROGESS = 'LOAD_DETAILS_PROGESS';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAIL = 'SIGN_UP_USER_FAIL';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const ADD_USER = 'ADD_USER';
export const USER_CHANGE_PROFILE_SUCCESS = 'USER_CHANGE_PROFILE_SUCCESS';
export const USER_CHANGE_PROFILE_FAIL = 'USER_CHANGE_PROFILE_FAIL';

export const CHANGE_MODAL = 'CHANGE_MODAL';

export const UPDATE_STAR_RATE = 'UPDATE_STAR_RATE';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';

export const UPDATE_PRODUCT_FAVORITE = 'UPDATE_PRODUCT_FAVORITE';
export const UPDATE_USER_FAVORITE = 'UPDATE_USER_FAVORITE';

