export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_DETAILS_SUCCESS = 'LOAD_DETAILS_SUCCESS';

export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';

